apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-observability-daily
  namespace: longhorn-system
spec:
  cron: "0 2 * * *"
  task: "backup"
  groups:
    - observability
  retain: 3
  concurrency: 1
