services:
  nginx:
    container_name: nginx
    build:
      context: ./7. application/nginx
    environment:
      - STATIC_PROXY_HOST_HEADER=minio.localhost
      - STATIC_SERVICE=http://minikube
      - BACK_END_SERVICE=http://back-end:3000
      - FORCES_IP=true
      - DNS_RESOLVER=127.0.0.11
    ports:
      - "8080:8080"
    networks:
      - minikube

  back-end:
    container_name: back-end
    build:
      context: ./7. application/back-end
      args:
        - NPM_OMIT_DEV=optional
      extra_hosts:
        - docker-nexus.localhost:192.168.49.2
        - nexus.localhost:192.168.49.2
    command: npm run watch-build-start
    environment:
      - NODE_ENV=dev
      - DB_DNORIO_POSTGRES_SCHEMA=public
      - DB_DNORIO_POSTGRES_USER=postgres
      - DB_DNORIO_POSTGRES_PASS=passwordinitial
      - DB_DNORIO_POSTGRES_HOST=minikube
      - DB_DNORIO_POSTGRES_DATA_PORT=54322
      - DB_DNORIO_POSTGRES_DATABASE=postgres
    volumes:
      - ./7. application/back-end/src:/usr/src/app/src
      - ./7. application/back-end/node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - minikube

networks:
  minikube:
    external: true
