---
apiVersion: v1
kind: LimitRange
metadata:
  name: app-limits
  namespace: minio
spec:
  limits:
  - default:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 1Gi
    defaultRequest:
      cpu: 10m
      memory: 64Mi
      ephemeral-storage: 50Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: app-limits
  namespace: kubecost
spec:
  limits:
  - default:
      cpu: 200m
      memory: 512Mi
      ephemeral-storage: 1Gi
    defaultRequest:
      cpu: 10m
      memory: 128Mi
      ephemeral-storage: 50Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: app-limits
  namespace: ingress-nginx
spec:
  limits:
  - default:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 1Gi
    defaultRequest:
      cpu: 10m
      memory: 64Mi
      ephemeral-storage: 50Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: app-limits
  namespace: cert-manager
spec:
  limits:
  - default:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 1Gi
    defaultRequest:
      cpu: 10m
      memory: 64Mi
      ephemeral-storage: 50Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: app-limits
  namespace: kubernetes-dashboard
spec:
  limits:
  - default:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 1Gi
    defaultRequest:
      cpu: 10m
      memory: 64Mi
      ephemeral-storage: 50Mi
    type: Container
