
apiVersion: v1
kind: LimitRange
metadata:
  name: app-limits
spec:
  limits:
  - default:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 1Gi
    defaultRequest:
        cpu: 10m
        memory: 64Mi
        ephemeral-storage: 50Mi
    type: Container
