//! `sources` table: monitored upstream feeds.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Discriminator matching the `sources.source_type` CHECK constraint.
///
/// Adding a new variant here MUST be paired with an updated migration
/// (relax the CHECK) — keep this enum and the SQL CHECK list in sync.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SourceType {
    /// Generic RSS/Atom feed.
    Rss,
    /// `GitHub` repository metadata (stars, forks, license, pushed_at).
    GithubRepo,
    /// `GitHub` releases stream (one row per release).
    GithubReleases,
    /// Single webpage fetched on demand.
    Webpage,
    /// `YouTube` channel.
    Youtube,
}

impl SourceType {
    /// String form persisted in Postgres. Stable wire contract.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            SourceType::Rss => "rss",
            SourceType::GithubRepo => "github_repo",
            SourceType::GithubReleases => "github_releases",
            SourceType::Webpage => "webpage",
            SourceType::Youtube => "youtube",
        }
    }

    /// Parse from the persisted string. `Err` carries the offending value
    /// for diagnostics.
    ///
    /// # Errors
    ///
    /// Returns the offending value when it is not one of the documented
    /// discriminators.
    pub fn parse(value: &str) -> Result<Self, String> {
        match value {
            "rss" => Ok(SourceType::Rss),
            "github_repo" => Ok(SourceType::GithubRepo),
            "github_releases" => Ok(SourceType::GithubReleases),
            "webpage" => Ok(SourceType::Webpage),
            "youtube" => Ok(SourceType::Youtube),
            other => Err(other.to_string()),
        }
    }
}

/// Strongly-typed row from `ai_radar.sources`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Source {
    /// Primary key (`UUIDv4` generated by Postgres `gen_random_uuid()`).
    pub id: Uuid,
    /// Human-readable label.
    pub name: String,
    /// Discriminator (see [`SourceType`]).
    pub source_type: SourceType,
    /// Upstream URL (feed, repo, page, channel).
    pub url: String,
    /// Whether the collector should poll this source.
    pub enabled: bool,
    /// Polling cadence in minutes; CHECK 1..=1440 in the migration.
    pub poll_interval_minutes: i32,
    /// Last successful poll timestamp (UTC).
    pub last_polled_at: Option<DateTime<Utc>>,
    /// Last collector error message, if any.
    pub last_error: Option<String>,
    /// Free-form metadata. Collectors may stash extra fields (e.g. RSS
    /// `etag`) without growing the schema.
    pub metadata_json: serde_json::Value,
    /// Row creation timestamp.
    pub created_at: DateTime<Utc>,
    /// Last update timestamp (maintained by `tg_touch_updated_at`).
    pub updated_at: DateTime<Utc>,
}

/// Payload accepted by `SourceRepository::create`.
#[derive(Debug, Clone, Deserialize)]
pub struct NewSource {
    /// Human-readable label.
    pub name: String,
    /// Discriminator.
    pub source_type: SourceType,
    /// Upstream URL.
    pub url: String,
    /// When omitted, the database keeps `enabled` at its default (`TRUE`).
    pub enabled: Option<bool>,
    /// When omitted, falls back to the table default (30 minutes).
    pub poll_interval_minutes: Option<i32>,
    /// Optional metadata blob.
    pub metadata_json: Option<serde_json::Value>,
}

impl NewSource {
    /// Validate the payload before sending it to Postgres.
    ///
    /// Catches obviously bad values up front so callers receive a clear
    /// `Validation` error instead of a generic database error.
    ///
    /// # Errors
    ///
    /// Returns a `Validation`-shaped string when name/URL are blank or
    /// `poll_interval_minutes` lies outside `[1, 1440]`.
    pub fn validate(&self) -> Result<(), String> {
        if self.name.trim().is_empty() {
            return Err("name must not be empty".into());
        }
        if self.url.trim().is_empty() {
            return Err("url must not be empty".into());
        }
        if let Some(p) = self.poll_interval_minutes {
            if !(1..=1440).contains(&p) {
                return Err(format!(
                    "poll_interval_minutes must be in [1, 1440], got {p}"
                ));
            }
        }
        Ok(())
    }
}

/// Patch payload accepted by `SourceRepository::update`.
///
/// Fields set to `None` are left untouched, matching the typical PATCH
/// semantics of the HTTP layer.
#[derive(Debug, Clone, Deserialize, Default)]
pub struct SourceUpdate {
    /// New display name.
    pub name: Option<String>,
    /// New URL.
    pub url: Option<String>,
    /// New enabled flag.
    pub enabled: Option<bool>,
    /// New polling cadence.
    pub poll_interval_minutes: Option<i32>,
    /// Replacement metadata blob.
    pub metadata_json: Option<serde_json::Value>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn source_type_roundtrips_through_strings() {
        for variant in [
            SourceType::Rss,
            SourceType::GithubRepo,
            SourceType::GithubReleases,
            SourceType::Webpage,
            SourceType::Youtube,
        ] {
            let s = variant.as_str();
            assert_eq!(SourceType::parse(s).unwrap(), variant);
        }
    }

    #[test]
    fn source_type_parse_rejects_unknown() {
        let err = SourceType::parse("twitter").unwrap_err();
        assert_eq!(err, "twitter");
    }

    #[test]
    fn new_source_validation_catches_blank_fields() {
        let err = NewSource {
            name: "  ".into(),
            source_type: SourceType::Rss,
            url: "https://x".into(),
            enabled: None,
            poll_interval_minutes: None,
            metadata_json: None,
        }
        .validate()
        .unwrap_err();
        assert!(err.contains("name"));
    }

    #[test]
    fn new_source_validation_caps_poll_interval() {
        let err = NewSource {
            name: "x".into(),
            source_type: SourceType::Rss,
            url: "https://x".into(),
            enabled: None,
            poll_interval_minutes: Some(0),
            metadata_json: None,
        }
        .validate()
        .unwrap_err();
        assert!(err.contains("[1, 1440]"));
    }
}
