# Jenkins LTS — SSDNodes CI (T-341)
# Ingress externo: jenkins-ingress.yaml | TLS via cert-manager

controller:
  componentName: jenkins-controller
  numExecutors: 0
  executorMode: "NORMAL"
  image:
    tag: "2.504.1-jdk17"
  admin:
    createSecret: true
    username: admin
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi
  serviceType: ClusterIP
  agentListenerServiceType: ClusterIP
  installPlugins:
    - kubernetes
    - git
    - workflow-aggregator
    - configuration-as-code
    - sonar
  JCasC:
    defaultConfig: true
    securityRealm: |-
      local:
        allowsSignup: false
        users:
        - id: "${chart-admin-username}"
          name: "Jenkins Admin"
          password: "${chart-admin-password}"
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false
  ingress:
    enabled: false

agent:
  enabled: true
  containerCap: 2
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi

persistence:
  enabled: true
  storageClass: local-path
  size: 20Gi

rbac:
  create: true

networkPolicy:
  enabled: false
