map $http_upgrade $connection_update {
  default upgrade;
  '' close;
}

map $host $dev_base_host {
  default localhost:8080;
}

map $host $dev_base_host_front {
  default localhost:8080;
}

map $host $qa_base_host {
  default localhost:8080;
}

server {
  absolute_redirect off;
  listen 8080 default_server;
  # resolver 127.0.0.11 valid=5s ipv6=off;
  proxy_max_temp_file_size 0;
  gzip on;
  gzip_disable "msie6";
  underscores_in_headers off;
  # gzip_vary on;
  # gzip_proxied any;
  # gzip_comp_level 1;
  # gzip_buffers 32 4k|16 8k;
  # gzip_http_version 1.1;
  # gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
  root /data/www;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header Host $host;
  proxy_set_header X-Req-Id $request_id;
  proxy_pass_request_headers on;

  location = /custom_403.html {
    internal;
  }
  location = /custom_404.html {
    internal;
  }
  location = /custom_502.html {
    internal;
  }

  error_page 403 = /custom_404.html;
  error_page 404 = /custom_404.html;
  error_page 502 = /custom_502.html;

  location = / {
    set $upstream http://minio.localhost/my-site/static/index.html;
    proxy_pass $upstream;
  }

  location ~ ^(/?.*)$ {
    set $upstream http://minio.localhost/my-site/static;
    proxy_pass $upstream$1$is_args$args;
  }
}