map $http_upgrade $connection_update {
  default upgrade;
  '' close;
}

server {
    listen 8080 default_server;
    http2 on;
    resolver $DNS_RESOLVER valid=5s ipv6=off;
    gzip on;
    gzip_disable "msie6";
    absolute_redirect off;
    proxy_max_temp_file_size 0;
    underscores_in_headers off;
    root /data/www;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $STATIC_PROXY_HOST_HEADER;
    proxy_set_header X-Req-Id $request_id;
    proxy_pass_request_headers on;

    location = / {
      set $upstream $STATIC_SERVICE/my-site/static/index.html;
      proxy_pass $upstream;
    }

    location ~ ^/geoip-metadata$ {
      add_header Content-Type application/json;
      return 200 '{"geoip2MetadataCountryBuild":$geoip2_metadata_Country_build,"geoip2MetadataCityBuild":$geoip2_metadata_city_build,"geoip2MetadataASNBuild":$geoip2_metadata_asn_build,"autonomousSystemOrganization":"$geoip2_org","geoip2RegionName":"$geoip2_region_name","geoip2City":"$geoip2_city"}';
    }

    location ~ ^/(.*)$ {
      proxy_pass $STATIC_SERVICE/my-site/static/$1$is_args$args;
	    proxy_intercept_errors on;
      error_page 404 =404 /404.html;
    }
}
