apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: quickstart
spec:
  version: 8.13.3
  image: docker-nexus.localhost/repository/docker-repo/logstash:8.13.3-custom.2
  services:
    - name: beats
      service:
        spec:
          ports:
          - port: 5044
            name: "filebeat"
            protocol: TCP
  count: 1
  elasticsearchRefs:
  - name: quickstart
    clusterName: qs
  configRef:
    secretName: quickstart-config
  pipelinesRef:
    secretName: quickstart-pipeline
  podTemplate:
    spec:
      terminationGracePeriodSeconds: 604800
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: logstash
        env:
        - name: LS_JAVA_OPTS
          value: -Xms256m -Xmx256m
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2Gi
            cpu: 2
        volumeMounts:
        - mountPath: /usr/share/logstash/dlq 
          name: dlq
          readOnly: false
  volumeClaimTemplates:
    - metadata:
        name: dlq 
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1536Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: quickstart-config
stringData:
  logstash.yml: |-
    pipeline.workers: 2
    log.level: info
    queue.drain: true
---
apiVersion: v1
kind: Secret
metadata:
  name: quickstart-pipeline
stringData:
  pipelines.yml: |-
    - pipeline.id: beats
      dead_letter_queue.enable: true
      path.dead_letter_queue: /usr/share/logstash/dlq 
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        filter {
          mutate {
            add_field => {
              "queue" => "beats"
            }
          }
          if ("beats_input_codec_plain_applied" in [tags]) { ## Beats json not applied
            if ([kubernetes][container][name] == "logstash") {
              # [2022-05-23T01:43:27,453][INFO ][logstash.outputs.elasticsearch][main]      
              grok {
                patterns_dir => ["/opt/logstash/custom_patterns"]
                match => { "message" => '\[%{ISO8601:app@timestamp}\]\[%{SEVERITY:severity} *\]%{GREEDYDATA:new_message}' }
                tag_on_failure => ["error_non_json", "grok_error_logstash_non_json"]
              }
              mutate {
                rename => { "new_message" => "message" }
                add_field => { "filter_type" => "logstash" }
                tag_on_failure => "mutate_error_logstash_non_json"
              }
            } else if ([kubernetes][container][name] == "kibana") {
              # [2024-05-09T15:06:46.557+00:00][INFO ][plugins.securitySolution.endpoint:user-artifact-packager:1.0.0] Last computed manifest not available yet
              grok {
                patterns_dir => ["/opt/logstash/custom_patterns"]
                match => { "message" => '\[%{ISO8601_DOT_FUSE:app@timestamp}\]\[%{SEVERITY:severity} *\]%{GREEDYDATA:new_message}' }
                tag_on_failure => ["error_non_json", "grok_error_kibana_non_json"]
              }
              mutate {
                rename => { "new_message" => "message" }
                add_field => { "filter_type" => "kibana" }
                tag_on_failure => "mutate_error_kibana_non_json"
              }
            } else if ([kubernetes][container][name] == "coredns") {
              # [INFO] 10.244.0.36:33312 - 61962 "AAAA IN quickstart-es-http.default.svc.cluster.local. udp 73 false 1232" NOERROR qr,aa,rd 155 0.000081505s
              grok {
                patterns_dir => ["/opt/logstash/custom_patterns"]
                match => { "message" => '\[%{SEVERITY:severity}\]%{GREEDYDATA:temp_message}' }
                tag_on_failure => ["error_non_json", "grok_error_coredns_non_json"]
              }
              mutate {
                rename => { "temp_message" => "message" }
                add_field => { "filter_type" => "coredns" }
                tag_on_failure => "mutate_error_coredns_non_json"
              }
            }
            # if ("error_non_json" not in [tags]) {
            #   mutate {
            #     remove_field => "[event][original]"
            #   }
            # }
          } else { ## Beats json decoded
            # Custom parsings
            if ([kubernetes][container][name] == "controller") {
              mutate {
                add_field => { "filter_type" => "controller_json" }
                tag_on_failure => "mutate_error_controller_json"
              }
              if [json][http][response][status] =~ /^2/ {
                mutate { add_field => { "severity" => "info" } }
              } else if [json][http][response][status] =~ /^3/ {
                mutate { add_field => { "severity" => "warn" } }
              } else {
                mutate { add_field => { "severity" => "error" } }
              }
            } else if ([kubernetes][container][name] == "filebeat" or [kubernetes][container][name] == "agent" or [kubernetes][container][name] == "apm-server") {
              mutate {
                rename => { "[json][@timestamp]" => "app@timestamp" }
                add_field => { "filter_type" => "%{[kubernetes][container][name]}_json" }
                rename => { "[json][log.level]" => "severity" }
                add_field => { "file" => "%{[json][log.origin][file.name]}:%{[json][log.origin][file.line]}" }
                tag_on_failure => "mutate_error_elastic_json"
              }
              mutate {
                remove_field => ["[json][log.origin][file.name]", "[json][log.origin][file.line]"]
                tag_on_failure => "mutate_error_elastic_json"
              }
            } else if ([kubernetes][container][name] == "elasticsearch") {
              mutate {
                rename => { "[json][@timestamp]" => "app@timestamp" }
                add_field => { "filter_type" => "elasticsearch_json" }
                rename => { "[json][log.level]" => "severity" }
                tag_on_failure => "mutate_error_elasticsearch_json"
              }
            } else if ([kubernetes][container][name] == "etcd") {
              mutate {
                remove_field => ["[json][message]"]
              }
              mutate {
                rename => { "[json][ts]" => "app@timestamp" }
                rename => { "[json][caller]" => "file" }
                rename => { "[json][msg]" => "message" }
                rename => { "[json][level]" => "severity" }
                add_field => { "filter_type" => "etcd_json" }
                tag_on_failure => "mutate_error_etcd_json"
              }
              # 2024-05-09T18:52:35.881931Z
              ruby {
                code => 'event.set("[app@timestamp]", event.get("[app@timestamp]")[0..22])'
                tag_on_exception => "mutate_error_etcd_timestamp"
              }
            } else if ([kubernetes][container][name] == "kibana") {
              # [2024-05-09T15:06:46.557+00:00][INFO ][plugins.securitySolution.endpoint:user-artifact-packager:1.0.0] Last computed manifest not available yet
              grok {
                patterns_dir => ["/opt/logstash/custom_patterns"]
                match => { "[json][message]" => '\[%{ISO8601_DOT_FUSE:app@timestamp}\]\[%{SEVERITY:severity} *\]%{GREEDYDATA:new_message}' }
                tag_on_failure => ["error_json", "grok_error_kibana_json"]
              }
              mutate {
                remove_field => ["[json][message]"]
                rename => { "new_message" => "message" }
                add_field => { "filter_type" => "kibana_json" }
                tag_on_failure => "mutate_error_kibana_json"
              }
            }

            # Move json properties to root level
            ruby {
              code => '
                event.get("[json]").each { |k,v|
                  event.set(k,v)
                }
              '
            }
            # if ("_rubyexception" not in [tags]) {
            #   mutate {
            #     remove_field => "json"
            #   }
            # }
          }

          # Coalesce severity by stream channel
          if ([severity]) {
            mutate {
              lowercase => ["severity"]
            }
          } else {
            if [stream] == "stdout" {
              mutate {
                add_field => {
                  "severity" => "process info"
                }
              }
            } else {
              mutate {
                add_field => {
                  "severity" => "process error"
                }
              }
            }
          }

          # Enforces precised app@timestamp if available
          date { match => [
            "[app@timestamp]",
            ## etcd sliced, nodejs
            "yyyy-MM-dd'T'HH:mm:ss.SSS",
            # Elastic json: filebeat, elasticsearch, agent, apm-server
            "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
            # logstash
            "yyyy-MM-dd'T'HH:mm:ss,SSS",
            # kibana
            "yyyy-MM-dd'T'HH:mm:ss.SSSZZ",
            # etc
            "yyyy-MM-dd'T'HH:mm:ss,SSSSSS",
            # kafka
            "yyyy-MM-dd HH:mm:ss,SSS",
            # postgres
            "yyyy-MM-dd HH:mm:ss.SSS 'UTC'"
          ] }

          mutate {
            replace => { "[data_stream][dataset]" => "%{[kubernetes][container][name]}" }
          }
        }

        output {
          elasticsearch {
            hosts => [ "${QS_ES_HOSTS}" ]
            user => "${QS_ES_USER}"
            password => "${QS_ES_PASSWORD}"
            ssl_certificate_authorities => "${QS_ES_SSL_CERTIFICATE_AUTHORITY}"
            data_stream => true
            # data_stream_dataset => "%{[kubernetes][container][name]}"
            # index => "logs-generic-%{[kubernetes][namespace]}-%{[kubernetes][container][name]}-%{+YYYY.MM.dd}"
            action => "create"
          }
        }

    - pipeline.id: dlq_read
      dead_letter_queue.enable: false
      config.string: |
        input {
          dead_letter_queue {
            path => "/usr/share/logstash/dlq" 
            commit_offsets => true
            pipeline_id => "beats"
            clean_consumed => true
          }
        }
        filter {
          mutate {
            add_field => {
              "queue" => "dlq_read"
            }
          }
        }
        output {
          elasticsearch {
            hosts => [ "${QS_ES_HOSTS}" ]
            user => "${QS_ES_USER}"
            password => "${QS_ES_PASSWORD}"
            ssl_certificate_authorities => "${QS_ES_SSL_CERTIFICATE_AUTHORITY}"
            action => "create"
          }
        }