apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: quickstart
spec:
  version: 8.17.1
  image: docker-nexus.localhost/repository/docker-repo/logstash:8.17.1-custom.3
  services:
    - name: beats
      service:
        spec:
          ports:
            - port: 5044
              name: "filebeat"
              protocol: TCP
  count: 1
  elasticsearchRefs:
    - name: quickstart
      clusterName: qs
  configRef:
    secretName: quickstart-config
  pipelinesRef:
    secretName: quickstart-pipeline
  podTemplate:
    spec:
      terminationGracePeriodSeconds: 604800
      imagePullSecrets:
        - name: regsecret
      containers:
        - name: logstash
          env:
            - name: LS_JAVA_OPTS
              value: -Xms256m -Xmx256m
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 2
          volumeMounts:
            - mountPath: /usr/share/logstash/dlq
              name: dlq
              readOnly: false
  volumeClaimTemplates:
    - metadata:
        name: dlq
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1536Mi
---
apiVersion: v1
kind: Secret
metadata:
  name: quickstart-config
stringData:
  logstash.yml: |-
    pipeline.workers: 2
    log.level: info
    queue.drain: true
---
apiVersion: v1
kind: Secret
metadata:
  name: quickstart-pipeline
stringData:
  pipelines.yml: |-
    - pipeline.id: beats
      dead_letter_queue.enable: true
      path.dead_letter_queue: /usr/share/logstash/dlq 
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        filter {
          mutate {
            add_field => {
              "queue" => "beats"
            }
          }
          if ("beats_input_codec_plain_applied" in [tags] and [message] and [kubernetes][container][name]) { ## Beats json not applied
            if ([kubernetes][container][name] == "logstash") {
              # [2022-05-23T01:43:27,453][INFO ][logstash.outputs.elasticsearch][main]      
              grok {
                patterns_dir => ["/opt/logstash/custom_patterns"]
                match => { "message" => '\[%{ISO8601:app@timestamp}\]\[%{SEVERITY:severity} *\]%{GREEDYDATA:new_message}' }
                tag_on_failure => ["error_non_json", "grok_error_logstash_non_json"]
              }
              mutate {
                rename => { "new_message" => "message" }
                add_field => { "filter_type" => "logstash" }
                tag_on_failure => "mutate_error_logstash_non_json"
              }
            } else if ([kubernetes][container][name] == "kibana") {
              # [2024-05-09T15:06:46.557+00:00][INFO ][plugins.securitySolution.endpoint:user-artifact-packager:1.0.0] Last computed manifest not available yet
              grok {
                patterns_dir => ["/opt/logstash/custom_patterns"]
                match => { "message" => '\[%{ISO8601_DOT_FUSE:app@timestamp}\]\[%{SEVERITY:severity} *\]%{GREEDYDATA:new_message}' }
                tag_on_failure => ["error_non_json", "grok_error_kibana_non_json"]
              }
              mutate {
                rename => { "new_message" => "message" }
                add_field => { "filter_type" => "kibana" }
                tag_on_failure => "mutate_error_kibana_non_json"
              }
            } else if ([kubernetes][container][name] == "coredns") {
              # [INFO] 10.244.0.36:33312 - 61962 "AAAA IN quickstart-es-http.default.svc.cluster.local. udp 73 false 1232" NOERROR qr,aa,rd 155 0.000081505s
              grok {
                patterns_dir => ["/opt/logstash/custom_patterns"]
                match => { "message" => '\[%{SEVERITY:severity}\]%{GREEDYDATA:new_message}' }
                tag_on_failure => ["error_non_json", "grok_error_coredns_non_json"]
              }
              mutate {
                rename => { "new_message" => "message" }
                add_field => { "filter_type" => "coredns" }
                tag_on_failure => "mutate_error_coredns_non_json"
              }
            } else if ([kubernetes][container][name] == "manager") { # elastic operator
              mutate {
                rename => { "log.level" => "severity" }
                add_field => { "filter_type" => "elastic_operator_non_json" }
                tag_on_failure => "mutate_error_elastic_operator_non_json"
              }
            } else if ([kubernetes][container][name] == "nexus") {
              # 2024-05-10 01:20:00,345+0000 INFO  [quartz-12-thread-20] *SYSTEM org.sonatype.nexus.quartz.internal.task.QuartzTaskInfo - Task 'Storage facet cleanup' [repository.storage-facet-cleanup] state change RUNNING -> WAITING (OK)
              grok {
                patterns_dir => ["/opt/logstash/custom_patterns"]
                match => { "message" => '%{DATE_SPACE_COMMA:app@timestamp}\+0000 +%{SEVERITY:severity} +%{GREEDYDATA:new_message}' }
                tag_on_failure => ["error_non_json", "grok_error_nexus"]
              }
              mutate {
                rename => { "new_message" => "message" }
                add_field => { "filter_type" => "nexus" }
                tag_on_failure => "mutate_error_nexus"
              }
            } else if (
              [kubernetes][container][name] == "kube-scheduler"
              or [kubernetes][container][name] == "kube-proxy"
              or [kubernetes][container][name] == "storage-provisioner"
              or [kubernetes][container][name] == "kube-apiserver"
              or [kubernetes][container][name] == "kube-controller-manager"
              or [kubernetes][container][name] == "metrics-server"
              or [kubernetes][container][name] == "controller"
            ) {
              ## kube-scheduler
              # I0509 20:14:26.186104       1 shared_informer.go:320] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
              ## kube-proxy
              # I0509 20:14:27.376734       1 shared_informer.go:320] Caches are synced for service config
              ## kube-controller-manager
              # I0509 21:53:33.951322       1 replica_set.go:676] "Finished syncing" logger="replicaset-controller" kind="ReplicaSet" key="ingress-nginx/ingress-nginx-controller-69f599888b" duration="5.069868ms"
              ## metrics-server
              # I0509 20:15:23.999251       1 server.go:191] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
              ## storage-provisioner
              # I0509 20:15:06.538039       1 event.go:282] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"k8s.io-minikube-hostpath", UID:"00d4e583-fb5b-492d-8ad8-4106b0385129", APIVersion:"v1", ResourceVersion:"95277", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' minikube_33e7b30f-9b6f-4245-8baf-b2d670cea124 became leader
              ## kube-apiserver
              # I0509 20:14:26.062026       1 controller.go:139] Starting OpenAPI controller
              ## controller (ingress controller, sometimes)
              # I0510 14:42:30.585503       7 store.go:440] "Found valid IngressClass" ingress="nexus/nexus-ingress" ingressclass="nginx"
              grok {
                patterns_dir => ["/opt/logstash/custom_patterns"]
                match => { "message" => '%{SEVERITY:temp_severity}\d{4} \d{2}:\d{2}:\d{2}\.\d{6} +\d %{ANY_WITHOUT_RIGHT_COLCHETES:file}\]' }
                tag_on_failure => ["grok_error_k8s"]
              }
              mutate {
                add_field => { "filter_type" => "k8s" }
              }
              if ("grok_error_k8s" not in [tags]) {
                if ([temp_severity] == "I") {
                  mutate {
                    add_field => { "severity" => "info" }
                    remove_field => ["temp_severity"]
                    tag_on_failure => "mutate_error_k8s"
                  }
                } else if ([temp_severity] == "W") {
                  mutate {
                    add_field => { "severity" => "warn" }
                    remove_field => ["temp_severity"]
                    tag_on_failure => "mutate_error_k8s"
                  }
                } else if ([temp_severity] == "E") {
                  mutate {
                    add_field => { "severity" => "error" }
                    remove_field => ["temp_severity"]
                    tag_on_failure => "mutate_error_k8s"
                  }
                }
              }
            } else if ([kubernetes][container][name] == "postgres") {
              # 2024-05-09 20:19:41.476 UTC [48] LOG: checkpoint complete: wrote 44 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.111 s, sync=0.006 s, total=4.126 s; sync files=11, longest=0.004 s, average=0.001 s; distance=261 kB, estimate=261 kB; lsn=0/1531A10, redo lsn=0/15319D8
              grok {
                patterns_dir => ["/opt/logstash/custom_patterns"]
                match => { "message" => '%{DATE_DOT_MILLIS_UTC:app@timestamp} \[\d+\] %{SEVERITY:severity}: +%{GREEDYDATA:new_message}' }
                tag_on_failure => ["error_non_json", "grok_error_postgres"]
              }
              mutate {
                rename => { "new_message" => "message" }
                add_field => { "filter_type" => "postgres" }
                tag_on_failure => "mutate_error_postgres"
              }
            }
            if ("error_non_json" not in [tags] and [event]) {
              mutate {
                remove_field => "[event][original]"
              }
            }
          } else if ([kubernetes][container][name]) { ## Beats json decoded
            # Custom parsings
            if ([kubernetes][container][name] == "controller" or [kubernetes][container][name] == "my-site-nginx") { # ingress controller
              mutate {
                add_field => { "filter_type" => "controller_json" }
                tag_on_failure => "mutate_error_controller_json"
              }
              if ([json][http][response][status]) {
                if [json][http][response][status] >= 300 {
                  mutate { add_field => { "severity" => "error" } }
                } else if [json][http][response][status] >= 200 {
                  mutate { add_field => { "severity" => "info" } }
                } else {
                  mutate { add_field => { "severity" => "warn" } }
                }
              }
            } else if ([kubernetes][container][name] =="my-site-back-end") {
              mutate {
                rename => { "[json][event]" => "action" }
              }
            }else if ([kubernetes][container][name] == "filebeat" or [kubernetes][container][name] == "agent" or [kubernetes][container][name] == "apm-server") {
              mutate {
                rename => { "[json][@timestamp]" => "app@timestamp" }
                add_field => { "filter_type" => "%{[kubernetes][container][name]}_json" }
                rename => { "[json][log.level]" => "severity" }
                add_field => { "file" => "%{[json][log.origin][file.name]}:%{[json][log.origin][file.line]}" }
                tag_on_failure => "mutate_error_elastic_json"
              }
              mutate {
                remove_field => ["[json][log.origin][file.name]", "[json][log.origin][file.line]"]
                tag_on_failure => "mutate_error_elastic_json"
              }
            } else if ([kubernetes][container][name] == "elasticsearch") {
              mutate {
                rename => { "[json][@timestamp]" => "app@timestamp" }
                add_field => { "filter_type" => "elasticsearch_json" }
                rename => { "[json][log.level]" => "severity" }
                tag_on_failure => "mutate_error_elasticsearch_json"
              }
            } else if ([kubernetes][container][name] == "etcd") {
              mutate {
                remove_field => ["[json][message]"]
              }
              mutate {
                rename => { "[json][ts]" => "app@timestamp" }
                rename => { "[json][caller]" => "file" }
                rename => { "[json][msg]" => "message" }
                rename => { "[json][level]" => "severity" }
                add_field => { "filter_type" => "etcd_json" }
                tag_on_failure => "mutate_error_etcd_json"
              }
              # 2024-05-09T18:52:35.881931Z
              ruby {
                code => '
                  if event.get("[app@timestamp]")
                    event.set("[app@timestamp]", event.get("[app@timestamp]")[0..22])
                  end
                '
                tag_on_exception => "mutate_error_etcd_timestamp"
              }
            } else if ([kubernetes][container][name] == "kibana") {
              # [2024-05-09T15:06:46.557+00:00][INFO ][plugins.securitySolution.endpoint:user-artifact-packager:1.0.0] Last computed manifest not available yet
              grok {
                patterns_dir => ["/opt/logstash/custom_patterns"]
                match => { "[json][message]" => '\[%{ISO8601_DOT_FUSE:app@timestamp}\]\[%{SEVERITY:severity} *\]%{GREEDYDATA:new_message}' }
                tag_on_failure => ["error_json", "grok_error_kibana_json"]
              }
              mutate {
                remove_field => ["[json][message]"]
                rename => { "new_message" => "message" }
                add_field => { "filter_type" => "kibana_json" }
                tag_on_failure => "mutate_error_kibana_json"
              }
            }

            # Move json properties to root level
            ruby {
              code => '
                json_fields = event.get("[json]")
                if json_fields.is_a?(Hash)
                  json_fields.each { |k,v|
                    if (k != "@timestamp")
                      event.set(k,v)
                    end
                  }
                end
              '
            }
            if ("_rubyexception" not in [tags]) {
              mutate {
                remove_field => "json"
              }
            }
          }

          # Coalesce severity by stream channel
          if ([severity]) {
            mutate {
              lowercase => ["severity"]
            }
          } else {
            if [stream] == "stdout" {
              mutate {
                add_field => {
                  "severity" => "process info"
                }
              }
            } else {
              mutate {
                add_field => {
                  "severity" => "process error"
                }
              }
            }
          }

          # Enforces precised app@timestamp if available
          if ([app@timestamp]) {
            date { match => [
              "[app@timestamp]",
              ## etcd sliced, nodejs
              "yyyy-MM-dd'T'HH:mm:ss.SSS",
              # Elastic json: filebeat, elasticsearch, agent, apm-server
              "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
              # logstash
              "yyyy-MM-dd'T'HH:mm:ss,SSS",
              # kibana
              "yyyy-MM-dd'T'HH:mm:ss.SSSZZ",
              # etc
              "yyyy-MM-dd'T'HH:mm:ss,SSSSSS",
              # kafka, nexus
              "yyyy-MM-dd HH:mm:ss,SSS",
              # postgres
              "yyyy-MM-dd HH:mm:ss.SSS 'UTC'"
            ] }
          }

          if ([data_stream][dataset]) {
            mutate {
              replace => { "[data_stream][dataset]" => "%{[kubernetes][container][name]}" }
            }
          }
        }

        output {
          elasticsearch {
            hosts => [ "${QS_ES_HOSTS}" ]
            user => "${QS_ES_USER}"
            password => "${QS_ES_PASSWORD}"
            ssl_certificate_authorities => "${QS_ES_SSL_CERTIFICATE_AUTHORITY}"
            data_stream => true
            # data_stream_dataset => "%{[kubernetes][container][name]}"
            # index => "logs-generic-%{[kubernetes][namespace]}-%{[kubernetes][container][name]}-%{+YYYY.MM.dd}"
            action => "create"
          }
        }

    - pipeline.id: dlq_read
      dead_letter_queue.enable: false
      config.string: |
        input {
          dead_letter_queue {
            path => "/usr/share/logstash/dlq" 
            commit_offsets => true
            pipeline_id => "beats"
            clean_consumed => true
          }
        }
        filter {
          mutate {
            add_field => {
              "queue" => "dlq_read"
            }
          }
        }
        output {
          elasticsearch {
            hosts => [ "${QS_ES_HOSTS}" ]
            user => "${QS_ES_USER}"
            password => "${QS_ES_PASSWORD}"
            ssl_certificate_authorities => "${QS_ES_SSL_CERTIFICATE_AUTHORITY}"
            action => "create"
          }
        }
