apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: nexus
    name: nexus
  name: nexus
---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
  namespace: nexus
  labels:
    app: nexus
type: Opaque
data:
  NEXUS_USER: cG9zdGdyZXM=
  NEXUS_PASSWORD: cGFzc3dvcmRpbml0aWFs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-volume
  namespace: nexus
  labels:
    type: nexus
    app: nexus
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/nexus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-volume-claim
  namespace: nexus
  labels:
    app: nexus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: 'sonatype/nexus3:3.66.0'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: /nexus-data
              name: nexusdata
      initContainers:
        - name: volume-mount-hack-nexus
          image: busybox
          command: ["sh", "-c", "chown -R 200:200 /nexus-data"]
          volumeMounts:
            - name: nexusdata
              mountPath: /nexus-data      
      volumes:
        - name: nexusdata
          persistentVolumeClaim:
            claimName: nexus-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
spec:
  selector:
    app: nexus
  type: NodePort
  ports:
    - name: tcp-port
      port: 8081
      targetPort: 8081
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: nexus
spec:
  rules:
    - host: nexus.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus-service
                port:
                  number: 8081