apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  annotations:
    eck.k8s.elastic.co/orchestration-hints: '{"no_transient_settings":true,"service_accounts":true,"desired_nodes":{"version":11,"hash":"1930358945"}}'
    elasticsearch.k8s.elastic.co/cluster-uuid: ISHaRu4iQ9iWdJlhaoZ4uw
  name: oci-logs
  namespace: elastic-system
spec:
  auth: {}
  http:
    service:
      metadata: {}
      spec: {}
    tls:
      certificate: {}
  monitoring:
    logs: {}
    metrics: {}
  nodeSets:
  - name: default
    count: 1
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: longhorn-1
    config:
      node.store.allow_mmap: false
      indices.memory.index_buffer_size: 5%
      indices.queries.cache.size: 2%
      indices.fielddata.cache.size: 2%
      thread_pool.search.size: 2
      thread_pool.write.size: 2
    podTemplate:
      spec:
        imagePullSecrets:
        - name: regcred
        containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms1g -Xmx1g"
          resources:
            limits:
              memory: 2Gi
              cpu: 600m
              ephemeral-storage: 8Gi
            requests:
              memory: 2Gi
              cpu: 200m

          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - |
                #!/usr/bin/env bash
                set -e
                curl -nk https://localhost:9200
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command:
              - bash
              - -c
              - curl -nk https://localhost:9200
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  transport:
    service:
      metadata: {}
      spec: {}
    tls:
      certificate: {}
      certificateAuthorities: {}
  updateStrategy:
    changeBudget: {}
  version: 8.11.0
