apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elastic-stack-ingress
  namespace: elastic-system
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns01"
    # Upload limits for large log queries/bulk imports
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    # SSL Passthrough not strictly needed if we terminate here, but Kibana/ES communicate in HTTPS backend
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - kibana.dnor.io
    - es.dnor.io
    secretName: elk-tls
  rules:
  - host: kibana.dnor.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oci-logs-kb-http
            port:
              number: 5601
  - host: es.dnor.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oci-logs-es-http
            port:
              number: 9200
