apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  annotations:
    association.k8s.elastic.co/es-conf-944678874: '{"authSecretName":"oci-logstash-elastic-system-oci-logs-logstash-user","authSecretKey":"elastic-system-oci-logstash-elastic-system-oci-logs-logstash-user","isServiceAccount":false,"caCertProvided":true,"caSecretName":"oci-logstash-logstash-es-elastic-system-oci-logs-ca","url":"https://oci-logs-es-http.elastic-system.svc:9200","version":"8.11.0"}'
  name: oci-logstash
  namespace: elastic-system
spec:
  configRef:
    secretName: logstash-config
  count: 1
  elasticsearchRefs:
  - clusterName: oci-logs
    name: oci-logs
  monitoring:
    logs: {}
    metrics: {}
  pipelinesRef:
    secretName: logstash-pipeline
  podTemplate:
    metadata:
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - env:
        - name: LS_JAVA_OPTS
          value: "-Xms512m -Xmx512m -XX:MaxMetaspaceSize=256m -Xss256k -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
        - name: LOGSTASH_USER
          value: "elastic"
        - name: LOGSTASH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: oci-logs-es-elastic-user
              key: elastic
        name: logstash
        image: docker.elastic.co/logstash/logstash:8.11.0
        resources:
          limits:
            memory: 1536Mi
            cpu: 600m
            ephemeral-storage: 4Gi
          requests:
            memory: 1Gi
            cpu: 200m
        volumeMounts:
        - mountPath: /opt/logstash/custom_patterns
          name: patterns-vol
        - mountPath: /usr/share/logstash/dlq
          name: dlq-vol
      volumes:
      - configMap:
          name: logstash-patterns
        image: docker.elastic.co/logstash/logstash:8.11.0
        name: patterns-vol
  services:
  - name: beats
    service:
      spec:
        ports:
        - name: filebeat
          port: 5044
          protocol: TCP
  version: 8.11.0
  volumeClaimTemplates:
  - metadata:
      name: dlq-vol
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 32Mi
      storageClassName: longhorn
  - metadata:
      name: logstash-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: longhorn
