apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: nexus
    name: nexus
  name: nexus
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: nexus-secret
#   namespace: nexus
#   labels:
#     app: nexus
# type: Opaque
# data:
#   NEXUS_USER: cG9zdGdyZXM=
#   NEXUS_PASSWORD: cGFzc3dvcmRpbml0aWFs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
  namespace: nexus
  labels:
    type: nexus
    app: nexus
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/nexus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: nexus
  labels:
    app: nexus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: 'sonatype/nexus3:3.67.1-java11'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
            - containerPort: 18444
              protocol: TCP
            - containerPort: 18445
              protocol: TCP
          volumeMounts:
            - mountPath: /nexus-data
              name: nexusdata
      initContainers:
        - name: volume-mount-hack-nexus
          image: busybox
          command: ["sh", "-c", "chown -R 200:200 /nexus-data"]
          volumeMounts:
            - name: nexusdata
              mountPath: /nexus-data      
      volumes:
        - name: nexusdata
          persistentVolumeClaim:
            claimName: nexus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
spec:
  selector:
    app: nexus
  type: NodePort
  ports:
    - name: tcp-port
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: docker-tcp-port
      port: 18444
      targetPort: 18444
      protocol: TCP
    - name: docker-tcp-port-https
      port: 18445
      targetPort: 18445
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: nexus
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 400m
spec:
  rules:
    - host: nexus.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus-service
                port:
                  number: 8081
    - host: docker-nexus.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus-service
                port:
                  number: 18444
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: postgres
    name: postgres
  name: postgres