from fastapi import Query
from typing import Optional
from datetime import datetime

back_end_raw_logs_schema = {
  "columns_to_select": [
    '_index',
    '_id',
    'log.file.path',
    'host.architecture',
    'host.name',
    'host.os.platform',
    # 'agent',
    'req-id',
    'apm.transaction.id',
    'apm.trace.id',
    'input.type',
    # 'event',
    'environment',
    'kubernetes.namespace',
    'kubernetes.labels.app',
    'kubernetes.container.name',
    'kubernetes.pod.name',
    'message',
    '@timestamp',
    'stream',
    'ecs.version',
    'queue',
    'action',
    'app@timestamp',
    'session-id',
    'userProfileId',
    'user',
    'tags',
    'container.image.name',
    'container.id',
    'file',
    'severity',
    'data_stream.type',
    'data_stream.dataset',
    'data_stream.namespace'
  ],
  "left_join_conditions": {
    'userProfileId': ['userName', 'accessProfile', 'companyName']
  },
  "timestamp_column": "timestamp"
}

def back_end_query_params(
  timestampMin: datetime = Query(..., description="Minimum timestamp to filter the data"),
  timestampMax: datetime = Query(..., description="Maximum timestamp to filter the data"),
  id: Optional[str] = Query(None, description="ID to filter the data"),
  userProfileId: Optional[str] = Query(None, description="User Profile ID to filter the data"),
  user: Optional[str] = Query(None, description="User to filter the data"),
  message: Optional[str] = Query(None, description="Message to filter the data"),
  tags: Optional[str] = Query(None, description="Tags to filter the data"),
  action: Optional[str] = Query(None, description="Action to filter the data"),
  environment: Optional[str] = Query(None, description="Environment to filter the data"),
  kubernetes_namespace: Optional[str] = Query(None, description="Kubernetes Namespace to filter the data"),
  kubernetes_labels_app: Optional[str] = Query(None, description="Kubernetes Labels App to filter the data"),
  kubernetes_container_name: Optional[str] = Query(None, description="Kubernetes Container Name to filter the data"),
  kubernetes_pod_name: Optional[str] = Query(None, description="Kubernetes Pod Name to filter the data"),
  host_name: Optional[str] = Query(None, description="Host Name to filter the data"),
  host_architecture: Optional[str] = Query(None, description="Host Architecture to filter the data"),
  host_os_platform: Optional[str] = Query(None, description="Host OS Platform to filter the data"),
  severity: Optional[str] = Query(None, description="Severity to filter the data"),
  file: Optional[str] = Query(None, description="File to filter the data"),
  stream: Optional[str] = Query(None, description="Stream to filter the data"),
  queue: Optional[str] = Query(None, description="Queue to filter the data"),
  container_image_name: Optional[str] = Query(None, description="Container Image Name to filter the data"),
  container_id: Optional[str] = Query(None, description="Container ID to filter the data"),
  data_stream_type: Optional[str] = Query(None, description="Data Stream Type to filter the data"),
  data_stream_dataset: Optional[str] = Query(None, description="Data Stream Dataset to filter the data"),
  data_stream_namespace: Optional[str] = Query(None, description="Data Stream Namespace to filter the data"),
  limit: Optional[int] = Query(25, description="Limit of rows to be returned"),
  offset: Optional[int] = Query(0, description="Offset of rows to be returned"),
  orderBy: Optional[str] = Query(None, description="Order by column"),
  order: str = Query("asc", description="Order by direction")
):
  return {
    'eventTimestampMin': timestampMin,
    'eventTimestampMax': timestampMax,
    'limit': limit,
    'offset': offset,
    'orderBy': orderBy,
    'order': order,
    'filters_optional': {
      'id': id,
      'userProfileId': userProfileId,
      'user': user,
      'message': message,
      'tags': tags,
      'action': action,
      'environment': environment,
      'kubernetes_namespace': kubernetes_namespace,
      'kubernetes_labels_app': kubernetes_labels_app,
      'kubernetes_container_name': kubernetes_container_name,
      'kubernetes_pod_name': kubernetes_pod_name,
      'host_name': host_name,
      'host_architecture': host_architecture,
      'host_os_platform': host_os_platform,
      'severity': severity,
      'file': file,
      'stream': stream,
      'queue': queue,
      'container_image_name': container_image_name,
      'container_id': container_id,
      'data_stream_type': data_stream_type,
      'data_stream_dataset': data_stream_dataset,
      'data_stream_namespace': data_stream_namespace
    }
  }
