apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-coroot-clickhouse-shard0-0
  namespace: coroot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-2
