apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coroot-data
  namespace: coroot
  labels:
    app.kubernetes.io/instance: coroot
    app.kubernetes.io/name: coroot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-2
