apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-restored
  namespace: postgres
  labels:
    app: postgres
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  dataSource:
    name: manual-20251201-091805
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
