apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /my-site/static/$1
  name: my-site-ingress
  namespace: minio
spec:
  ingressClassName: nginx
  rules:
    - host: my-site.localhost
      http:
        paths:
          - path: /(.*)
            backend:
              service:
                name: minio-service
                port:
                  number: 9000
            pathType: ImplementationSpecific