---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
data:
  hsts: 'false'
  # use-gzip: 'true'
  use-geoip: 'false'
  use-geoip2: 'true'
  log-format-escape-json: 'true'
  log-format-upstream: '{"app@timestamp":"$time_iso8601_p1.$millisec","action":"Request received","message":"$request $status $request_time $geoip2_city_country_name - $geoip2_region_code - $geoip2_city ($geoip2_latitude, $geoip2_longitude) $http_user_agent","http":{"host":"$host","remote_addr":"$remote_addr","request":{"request":"$request","method":"$request_method","uri":"$uri","scheme":"$scheme","referer":"$http_referer","user_agent":"$http_user_agent","x_forwarded_for":"$http_x_forwarded_for","body_bytes_sent":"$body_bytes_sent","upstream_response_time":"$upstream_response_time","upstream_connect_time":"$upstream_connect_time"},"response":{"status":"$status"},"elapsed_time":"$request_time","proxy_host":"$proxy_host","country_code":"$geoip2_city_country_code","country_name":"$geoip2_city_country_name","city_id":"$geoip2_city_geoname_id","city_name":"$geoip2_city","latitude":"$geoip2_latitude","longitude":"$geoip2_longitude","region_code":"$geoip2_region_code","region_name":"$geoip2_region_name"},"req-id":"$request_id"}'
  use-forwarded-headers: "true"
  forwarded-for-header: "X-Forwarded-For"
  http-snippet: |
    map "$time_local:$msec" $time_local_ms { ~(^\S+)(\s+\S+):\d+\.(\d+)$ $1.$3$2; }
    map $time_iso8601 $time_iso8601_p1 {
      ~([^+]+) $1;
    }
    map $msec $millisec {
      ~\.([0-9]+)$ $1;
    }
