
apiVersion: v1
kind: LimitRange
metadata:
  name: longhorn-limits
  namespace: longhorn-system
spec:
  limits:
  - default:
      cpu: 250m
      memory: 256Mi
    defaultRequest:
        cpu: 50m
        memory: 128Mi
    type: Container
