apiVersion: v1
kind: Pod
metadata:
  name: check-df
  namespace: coroot
spec:
  nodeName: k8s-node-2
  containers:
  - name: check-df
    image: busybox
    command: ["/bin/sh", "-c", "df -h"]
  restartPolicy: Never
