services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    environment:
      - STATIC_PROXY_HOST_HEADER=minio.localhost
      - STATIC_SERVICE=http://minikube
      - BACK_END_SERVICE=http://back-end:3000
      - PY_BACK_END_SERVICE=http://back-end-py-metrics:3000
      - FORCES_IP=true
      - DNS_RESOLVER=127.0.0.11
    ports:
      - "8080:8080"
    networks:
      - minikube
    deploy:
      resources:
        limits:
          memory: 16M
          cpus: '0.4'
        reservations:
          memory: 8M
          cpus: '0.1'


  kafka:
    image: kafka
    hostname: kafka
    container_name: kafka
    build:
      context: ./kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_KRAFT_MODE: "true"
      CLUSTER_ID: "c5c6a30b-8236-4c11-a50f-e15f77e900e0"
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

  kafbat:
    hostname: kafbat
    container_name: kafbat
    image: ghcr.io/kafbat/kafka-ui:76c8d98
    ports:
      - 8080:8080
    volumes:
      - ./kafbat-config.yaml:/etc/kafbat/kafbat-config.yaml:ro
    environment:
      KAFBAT_CONFIG_PATH: /etc/kafbat/kafbat-config.yaml
      LOG_LEVEL: debug
      KAFKA_CLUSTERS_0_NAME: kraft-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

  kafka-client:
    image: confluentinc/cp-kafka:7.9.1
    command: sleep infinity
    # docker exec -it apps-kafka-client-1 kafka-topics --bootstrap-server kafka:9092 --list
    # docker exec -it apps-kafka-client-1 kafka-topics --bootstrap-server kafka:9092 --create --topic test --partitions 1 --replication-factor 1

  back-end:
    container_name: back-end
    build:
      context: ./back-end
      args:
        - NPM_OMIT_DEV=optional
      extra_hosts:
        - docker-nexus.localhost:192.168.49.2
        - nexus.localhost:192.168.49.2
        - minio.localhost:192.168.49.2
    command: npm run watch-build-start
    env_file:
      - ./back-end/.env
    environment:
      - DB_DNORIO_POSTGRES_HOST=minikube
      - DB_DNORIO_POSTGRES_PORT=54322
    volumes:
      - ./back-end/src:/usr/src/app/src
      - ./back-end/node_modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - minikube
    extra_hosts:
      - nexus.localhost:192.168.49.2
      - minio.localhost:192.168.49.2
      - minikube:192.168.49.2
    deploy:
      resources:
        limits:
          memory: 1536M
          cpus: '0.5'
        reservations:
          memory: 1024M
          cpus: '0.2'

  back-end-rs-axum:
    container_name: back-end-rs-axum
    image: back_end_rs_axum
    build:
      context: ./rs-axum-back-end
    volumes:
      - ./rs-axum-back-end/app:/app/app
      - $HOME/.aws:/root/.aws
    ports:
      - 3002:3000
      - 9232:5678
    env_file:
      - ./rs-axum-back-end/.env
    environment:
      - DB_HOST=minikube
      - DB_PORT=54322
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - minikube
    extra_hosts:
      - nexus.localhost:192.168.49.2
      - minio.localhost:192.168.49.2
      - minikube:192.168.49.2
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.4'
        reservations:
          memory: 64M
          cpus: '0.1'

  back-end-rs-vanilla:
    container_name: back-end-rs-vanilla
    image: back_end_rs_vanilla
    build:
      context: ./rs-vanilla-back-end
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      # - $HOME/.aws:/root/.aws
    ports:
      - 3003:3000
      - 9233:5678
    # env_file:
    #   - ./rs-vanilla-back-end/.env
    # environment:
    #   - DB_HOST=minikube
    #   - DB_PORT=54322
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 1s
      timeout: 5s
      retries: 4
      start_period: 20s
    networks:
      - minikube
    extra_hosts:
      - nexus.localhost:192.168.49.2
      - minio.localhost:192.168.49.2
      - minikube:192.168.49.2
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.4'
        reservations:
          memory: 64M
          cpus: '0.1'

  back-end-py-metrics:
    container_name: back-end-py-metrics
    image: back_end_py_metrics
    build:
      context: ./py-back-end
    # command: ["uvicorn", "app.main:app", "--reload", "--no-access-log", "--host", "0.0.0.0", "--port", "3000", "--no-server-header", "--log-config", "log_config.json"]
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "app.main:app", "--reload", "--no-access-log", "--host", "0.0.0.0", "--port", "3000", "--log-config", "log_config.json"]
    volumes:
      - ./py-back-end/app:/app/app
      - $HOME/.aws:/root/.aws
    ports:
      - 3001:3000
      - 9230:5678
    env_file:
      - ./py-back-end/.env
    environment:
      - DB_DNORIO_POSTGRES_HOST=minikube
      - DB_DNORIO_POSTGRES_PORT=54322
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - minikube
    extra_hosts:
      - nexus.localhost:192.168.49.2
      - minio.localhost:192.168.49.2
      - minikube:192.168.49.2
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 50M
          cpus: '0.2'

  tor:
    container_name: tor
    build:
      context: ./tor
    ports:
      - "9050:9050"
    networks:
      - minikube
    volumes:
      - ./tor/torrc:/etc/tor/torrc:ro
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'


  # pg:
  #   container_name: pg
  #   build:
  #     context: ./components/postgres
  #   networks:
  #     - minikube
  #   environment:
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=admin
  #     - PG_HOST=postgres

networks:
  minikube:
    external: true

volumes:
  kafka-data:
